export interface RecipeData {
    calories: number;
    carbohydrates: number;
    compound: number;
    contributor_id: number;
    date: string;
    description: string;
    food_types: string;
    ingredients: string;
    minutes: number;
    n_ingredients: number;
    n_steps: number;
    name: string;
    negative: number;
    neutral: number;
    positive: number;
    protein: number;
    rating: number;
    recipe_id: number;
    review: string;
    saturated_fat: number;
    sodium: number;
    steps: string;
    submitted: string;
    sugar: number;
    tags: string;
    total_fat: number;
    user_id: number;
}
